### PR TITLE
Serialize licenses 2

### PR DESCRIPTION
**Pull request by mtsfoni**

### CODE REVIEW

**Comment by mtsfoni** [comment]
@andreas-hilti This is a rebased version of #218. 

All the tests are green and multiple licences work with it.

I'm not 100% sure why the JSON change from 1.5 doesn't require changes in the library, but it seems the structure is still the same, just with more limitations. (I don't have much JSON schema experience.

Would you mind looking over it again? It looks good from my perspective.

**Review by andreas-hilti — APPROVED** [review]
Looks good to me.

**Comment by andreas-hilti** [comment]
> I'm not 100% sure why the JSON change from 1.5 doesn't require changes in the library, but it seems the structure is still the same, just with more limitations. (I don't have much JSON schema experience.

The current state of the library can represent everything that is allowed by 1.5. It would also allow a list of license expressions, which is no longer allowed by 1.5. This is the part that you'd need to handle to make sure that you comply with the specification.

**Comment by mtsfoni** [comment]
There are just some things that the library can not easily limit. One would also be allowed to create a licenses and expressions at the same time.
What bothers me about this solution is that the libraries model still works on a list of licensechoices which might confuse users that work along the schemas.

For now, I think it's more important to help people that suffer under the multiple licensechoice bug, though.

**Pull request merged**
