### PR TITLE
Update JsonSchema.Net

### PR DESCRIPTION
**Pull request by andreas-hilti**
Update JsonSchema.Net to version 5.3.1

Compare release notes:
https://docs.json-everything.net/rn-json-schema/
as well as the docs for Evaluation results:
https://docs.json-everything.net/schema/basics/#schema-results

### CODE REVIEW

**Comment by lfrancke** [comment]
Thank you very much!
It might make sense to add a test for the timestamps that triggered all of this?

**Comment by lfrancke** [comment]
Thank you!

**Comment by andreas-hilti** [comment]
> Thank you very much! It might make sense to add a test for the timestamps that triggered all of this?

Done.

**Comment by lfrancke** [comment]
Thank you! I can't really comment on the code changes itself but what I can see I like. Thanks!

**Pull request merged**
