### PR TITLE
Fix enums for protobuf serialization

### PR DESCRIPTION
**Pull request by andreas-hilti**

### CODE REVIEW

**Comment by andreas-hilti** [comment]
@mtsfoni As far as I can see, this would fix most of the issues with the protobuf serialization.

**Comment by andreas-hilti** [comment]
The only remaining issue that I see is related the certificationLevel
@jkowalleck Do you know why certificationLevel is an array of enums for json and xml, but a repeated string for protobuf?
https://github.com/CycloneDX/specification/blob/f18b992f8523728c17318a488dd716e5c677ae4c/schema/bom-1.6.proto#L2051
https://github.com/CycloneDX/specification/blob/f18b992f8523728c17318a488dd716e5c677ae4c/schema/bom-1.6.schema.json#L5141-L5209
https://github.com/CycloneDX/specification/blob/f18b992f8523728c17318a488dd716e5c677ae4c/schema/bom-1.6.xsd#L6481-L6696

**Comment by andreas-hilti** [comment]
The above commit fixes the fact that a string an not enum is used for Protobuf; whether the actual string values are the correct ones is unclear, in particular the proto file does not specify them.

**Comment by mtsfoni** [comment]
It looks like the enum value of certificationLevel are the same in the json-schema and xsd. I'd guess the "correct" way is to use those in the string array in the protobuf. Other libraries might not be able to parse the c# enum and vice versa.

Using a stupid switch case should be good enough for this single case.
Something like this?

``` csharp
public CertificationLevel CertificationLevelFromString(string value)
{
    switch (value)
    {
        case "none": return CertificationLevel.None;
        case "fips140-1-l1": return CertificationLevel.FIPS140_1_L1;
        case "fips140-1-l2": return CertificationLevel.FIPS140_1_L2;
        case "fips140-1-l3": return CertificationLevel.FIPS140_1_L3;
        case "fips140-1-l4": return CertificationLevel.FIPS140_1_L4;
        case "fips140-2-l1": return CertificationLevel.FIPS140_2_L1;
        case "fips140-2-l2": return CertificationLevel.FIPS140_2_L2;
        case "fips140-2-l3": return CertificationLevel.FIPS140_2_L3;
        case "fips140-2-l4": return CertificationLevel.FIPS140_2_L4;
        case "fips140-3-l1": return CertificationLevel.FIPS140_3_L1;
        case "fips140-3-l2": return CertificationLevel.FIPS140_3_L2;
        case "fips140-3-l3": return CertificationLevel.FIPS140_3_L3;
        case "fips140-3-l4": return CertificationLevel.FIPS140_3_L4;
        case "cc-eal1": return CertificationLevel.CC_EAL1;
        case "cc-eal1+": return CertificationLevel.CC_EAL1plus;
        case "cc-eal2": return CertificationLevel.CC_EAL2;
        case "cc-eal2+": return CertificationLevel.CC_EAL2plus;
        case "cc-eal3": return CertificationLevel.CC_EAL3;
        case "cc-eal3+": return CertificationLevel.CC_EAL3plus;
        case "cc-eal4": return CertificationLevel.CC_EAL4;
        case "cc-eal4+": return CertificationLevel.CC_EAL4plus;
        case "cc-eal5": return CertificationLevel.CC_EAL5;
        case "cc-eal5+": return CertificationLevel.CC_EAL5plus;
        case "cc-eal6": return CertificationLevel.CC_EAL6;
        case "cc-eal6+": return CertificationLevel.CC_EAL6plus;
        case "cc-eal7": return CertificationLevel.CC_EAL7;
        case "cc-eal7+": return CertificationLevel.CC_EAL7plus;
        case "other": return CertificationLevel.Other;
        case "unknown": return CertificationLevel.Unknown;
        default: return CertificationLevel.Null;
    }
}

public string CertificationlevelToString(CertificationLevel level)
{
    switch (level)
    {
        case CertificationLevel.None: return "none";
        case CertificationLevel.FIPS140_1_L1: return "fips140-1-l1";
        case CertificationLevel.FIPS140_1_L2: return "fips140-1-l2";
        case CertificationLevel.FIPS140_1_L3: return "fips140-1-l3";
        case CertificationLevel.FIPS140_1_L4: return "fips140-1-l4";
        case CertificationLevel.FIPS140_2_L1: return "fips140-2-l1";
        case CertificationLevel.FIPS140_2_L2: return "fips140-2-l2";
        case CertificationLevel.FIPS140_2_L3: return "fips140-2-l3";
        case CertificationLevel.FIPS140_2_L4: return "fips140-2-l4";
        case CertificationLevel.FIPS140_3_L1: return "fips140-3-l1";
        case CertificationLevel.FIPS140_3_L2: return "fips140-3-l2";
        case CertificationLevel.FIPS140_3_L3: return "fips140-3-l3";
        case CertificationLevel.FIPS140_3_L4: return "fips140-3-l4";
        case CertificationLevel.CC_EAL1: return "cc-eal1";
        case CertificationLevel.CC_EAL1plus: return "cc-eal1+";
        case CertificationLevel.CC_EAL2: return "cc-eal2";
        case CertificationLevel.CC_EAL2plus: return "cc-eal2+";
        case CertificationLevel.CC_EAL3: return "cc-eal3";
        case CertificationLevel.CC_EAL3plus: return "cc-eal3+";
        case CertificationLevel.CC_EAL4: return "cc-eal4";
        case CertificationLevel.CC_EAL4plus: return "cc-eal4+";
        case CertificationLevel.CC_EAL5: return "cc-eal5";
        case CertificationLevel.CC_EAL5plus: return "cc-eal5+";
        case CertificationLevel.CC_EAL6: return "cc-eal6";
        case CertificationLevel.CC_EAL6plus: return "cc-eal6+";
        case CertificationLevel.CC_EAL7: return "cc-eal7";
        case CertificationLevel.CC_EAL7plus: return "cc-eal7+";
        case CertificationLevel.Other: return "other";
        case CertificationLevel.Unknown: return "unknown";
        default: return "null";
    }
}
```

**Comment by andreas-hilti** [comment]
> It looks like the enum value of certificationLevel are the same in the json-schema and xsd. I'd guess the "correct" way is to use those in the string array in the protobuf. Other libraries might not be able to parse the c# enum and vice versa.
> 
> Using a stupid switch case should be good enough for this single case. 

Ok, let me change it.

**Pull request merged**
