### PR TITLE
Cdx1.6

### PR DESCRIPTION
**Pull request by andreas-hilti**

### CODE REVIEW

**Comment by andreas-hilti** [comment]
@mtsfoni I have merged main and I have fixed most tests. There are at the moment only 7 failures. One issue is for sure that something goes wrong when downgrading metadata tools (which is based on the protobuf serialization).

**Comment by mtsfoni** [comment]
The 1.6 branch is a wip with failing tests itself, so it's natuiral that this pr would have failing tests too.

Thank you a lot for the help. Is this ready to merge?

**Comment by andreas-hilti** [comment]
> The 1.6 branch is a wip with failing tests itself, so it's natuiral that this pr would have failing tests too.
> 
> Thank you a lot for the help. Is this ready to merge?

Yes, from my point of view the above 4 commits are fine and can be merged into your branch.
The remaining 4 failing tests all go back to the same issue related to metadata tools (from what I can see, the current protobuf serialization implementation only supports the legacy tools, not the components and services: https://github.com/CycloneDX/cyclonedx-dotnet-library/blob/a42f0bf823ed56aec0e939ed6f85c54669baafee/src/CycloneDX.Core/Models/Metadata.cs#L40-L66, but I don't see how this can be changed easily.)

**Comment by andreas-hilti** [comment]
The remaining issues are related to https://github.com/CycloneDX/specification/issues/276.

**Comment by andreas-hilti** [comment]
@mtsfoni https://github.com/andreas-hilti/cyclonedx-dotnet-library/commit/c3a4c70fa45b1a32f3b358e73a5e38bc16666120 would be a workaround for the above issue (it does not underlying issue, though). Like this, all tests would pass.

**Comment by mtsfoni** [comment]
> @mtsfoni [andreas-hilti@c3a4c70](https://github.com/andreas-hilti/cyclonedx-dotnet-library/commit/c3a4c70fa45b1a32f3b358e73a5e38bc16666120) would be a workaround for the above issue (it does not fix the underlying issue, though). Like this, all tests would pass.

Black magic. But the tests are green. I take it

**Pull request merged**
