### PR TITLE
fix issues with duplicates and missing main components

### PR DESCRIPTION
**Pull request by fnxpt**
Flatten Merge duplicates all the components/dependencies and skips the main component on metadata.
when merging the dependencies the graph is also broken because there isn't a connection with the boms main components

Fixes https://github.com/CycloneDX/cyclonedx-cli/issues/219
Fixes https://github.com/CycloneDX/cyclonedx-cli/issues/188

### CODE REVIEW

**Comment by fnxpt** [comment]
@coderpatros can you check and approve the workflow

**Comment by samwhite-gl** [comment]
@fnxpt thanks for opening this MR!

This bug is impacting users who are using this tool to merge their CycloneDX files as part of GitLab's Dependency Scanning solution.  @coderpatros is there anything we can do to help to get this reviewed and merged?

**Comment by coderpatros** [comment]
@fnxpt when determining if a component or tool is the same, I think package URLs and hashes, if present, should also be compared. Two components might be the "same" but have different provenance. Depending on that provenance the hashes can be different too.

**Comment by fnxpt** [comment]
For the tool I understand and Im going to add it, but for the component, shouldn't the bomref be enough (maybe just add the hash if there isn't a bomref)

**Comment by coderpatros** [comment]
@fnxpt the bomref isn't guaranteed to be a usable identifier outside of the context of a particular CDX BOM. The convention is to use PURLs, but it isn't a requirement. So depending on the generation tool it could be something like `component-1`, `component-2`, `component-3`, etc. And the bomrefs could be duplicated for different components in the two BOMs being merged.

The same goes for services.

**Comment by fnxpt** [comment]
Clear expect some changes either today or tomorrow

**Comment by coderpatros** [comment]
> Clear expect some changes either today or tomorrow

Thanks so much for the contribution, apologies for the delay in feedback. I've had some personal stuff going on.

**Comment by andreas-hilti** [comment]
@coderpatros Did you really intended to merge it at this stage? @fnxpt did not yet push any new changes. Some checks are still based on BOM-Ref equality.

**Comment by coderpatros** [comment]
@andreas-hilt, I'm going to tweak it myself to get a new version out.

**Comment by fnxpt** [comment]
sorry, but I have been busy with work and I was not able to make the changes.... @coderpatros thanks for following on this

**Pull request merged**
