### PR TITLE
Implement support for CycloneDX specification v1.4

### PR DESCRIPTION
**Pull request by coderpatros**

### CODE REVIEW

**Comment by stevespringett** [comment]
Is it possible to use annotations in C# to designate which version of the spec a field is supported in?

If you take a look at https://github.com/CycloneDX/cyclonedx-core-java/blob/master/src/main/java/org/cyclonedx/model/Bom.java as an example, you'll notice we created a custom annotation called VersionFilter. When the library serializes, it checks if the annotation exists and if it does, it checks to see if the version specified in the annotation equals the version of the spec being serialized.

**Comment by coderpatros** [comment]
That would certainly reduce a lot of boilerplate code @stevespringett 

How does that approach go with things like component type where valid values differ between the specs?

**Comment by stevespringett** [comment]
Component type is a corner case not currently supported by the library, but hash algs are supported with `>=` comparisons. See https://github.com/CycloneDX/cyclonedx-core-java/blob/master/src/main/java/org/cyclonedx/util/BomUtils.java

**Comment by coderpatros** [comment]
Cool, thanks for the suggestion. I haven't really been happy with the current approach, although functional. Mass code cleanup has commenced.

**Pull request merged**
